[package]
name = "bindings"
version = "0.1.0"
edition = "2021"

[dependencies]
mcm-api = { path = "../api" }
regex = { workspace = true }
ts-rs = { workspace = true }

[[bin]]
name = "bindings"
path = "main.rs"
